/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.myproject.vf;

import org.sleuthkit.autopsy.ingest.IngestModuleIngestJobSettings;
import org.sleuthkit.autopsy.ingest.IngestModuleIngestJobSettingsPanel;

/**
 *
 * @author stone
 */
public class VfModuleSettingsPanel  extends IngestModuleIngestJobSettingsPanel {

    private final VfModuleSettings settings;
    
    VfModuleSettingsPanel(VfModuleSettings settings) {
         this.settings = settings;
         initComponents();
         customizeComponents(settings);
    }
    
    private void customizeComponents(VfModuleSettings settings) {
         
        isAndroidRadioButton.setSelected(settings.isAndroid());
        isLinuxRadioButton.setSelected(settings.isLinux());
        isWindowsRadioButton.setSelected(settings.isWindows());
        isMacRadioButton.setSelected(settings.isMac());
    }

    @Override
    public IngestModuleIngestJobSettings getSettings() {
        return settings;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        isMacRadioButton = new javax.swing.JRadioButton();
        isWindowsRadioButton = new javax.swing.JRadioButton();
        isLinuxRadioButton = new javax.swing.JRadioButton();
        isAndroidRadioButton = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(isMacRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(isMacRadioButton, org.openide.util.NbBundle.getMessage(VfModuleSettingsPanel.class, "VfModuleSettingsPanel.isMacRadioButton.text")); // NOI18N
        isMacRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isMacRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(isWindowsRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(isWindowsRadioButton, org.openide.util.NbBundle.getMessage(VfModuleSettingsPanel.class, "VfModuleSettingsPanel.isWindowsRadioButton.text")); // NOI18N
        isWindowsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isWindowsRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(isLinuxRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(isLinuxRadioButton, org.openide.util.NbBundle.getMessage(VfModuleSettingsPanel.class, "VfModuleSettingsPanel.isLinuxRadioButton.text")); // NOI18N
        isLinuxRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isLinuxRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(isAndroidRadioButton);
        org.openide.awt.Mnemonics.setLocalizedText(isAndroidRadioButton, org.openide.util.NbBundle.getMessage(VfModuleSettingsPanel.class, "VfModuleSettingsPanel.isAndroidRadioButton.text")); // NOI18N
        isAndroidRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAndroidRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isMacRadioButton)
                    .addComponent(isWindowsRadioButton)
                    .addComponent(isLinuxRadioButton)
                    .addComponent(isAndroidRadioButton))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(isAndroidRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isLinuxRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isWindowsRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isMacRadioButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void isAndroidRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAndroidRadioButtonActionPerformed
        settings.setIsAndroid(isAndroidRadioButton.isSelected());
    }//GEN-LAST:event_isAndroidRadioButtonActionPerformed

    private void isLinuxRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isLinuxRadioButtonActionPerformed
        settings.setIsLinux(isLinuxRadioButton.isSelected());
    }//GEN-LAST:event_isLinuxRadioButtonActionPerformed

    private void isWindowsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isWindowsRadioButtonActionPerformed
        settings.setIsWindows(isWindowsRadioButton.isSelected());
    }//GEN-LAST:event_isWindowsRadioButtonActionPerformed

    private void isMacRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isMacRadioButtonActionPerformed
        settings.setIsMac(isMacRadioButton.isSelected());
    }//GEN-LAST:event_isMacRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton isAndroidRadioButton;
    private javax.swing.JRadioButton isLinuxRadioButton;
    private javax.swing.JRadioButton isMacRadioButton;
    private javax.swing.JRadioButton isWindowsRadioButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
}
