/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.myproject.vf;

import java.util.ArrayList;

/**
 *
 * @author stone
 */
public class AndroidPluginSetup extends javax.swing.JDialog {

    //variables for dialog to store user choice
    String volProfile;
    ArrayList plugins = new ArrayList();

    /**
     * Creates new form AndroidPluginSetup
     */
    /**
     * Creates new form AndroidPluginSetup
     */
    public AndroidPluginSetup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AndroidPluginSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveAndroidSettingsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pstree = new javax.swing.JCheckBox();
        pslist = new javax.swing.JCheckBox();
        limeInfo = new javax.swing.JCheckBox();
        arpTable = new javax.swing.JCheckBox();
        linuxBanner = new javax.swing.JCheckBox();
        bashHistory = new javax.swing.JCheckBox();
        bashEnvVar = new javax.swing.JCheckBox();
        bashHashTable = new javax.swing.JCheckBox();
        checkAfInfo = new javax.swing.JCheckBox();
        checkCredsStruct = new javax.swing.JCheckBox();
        checkEvt = new javax.swing.JCheckBox();
        checkModules = new javax.swing.JCheckBox();
        checkSyscall = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        checkSyscallArm = new javax.swing.JCheckBox();
        dentryCache = new javax.swing.JCheckBox();
        kernelDebugBuffer = new javax.swing.JCheckBox();
        findELF = new javax.swing.JCheckBox();
        ifconfigComm = new javax.swing.JCheckBox();
        enumerateFiles = new javax.swing.JCheckBox();
        hiddenKernelModules = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        iomemComm = new javax.swing.JCheckBox();
        keyboardNotifiers = new javax.swing.JCheckBox();
        ldrModules = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        libraryList = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        appsPromSoc = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        loadedKernelModules = new javax.swing.JCheckBox();
        listOpenFiles = new javax.swing.JCheckBox();
        suspiciousProcessMappings = new javax.swing.JCheckBox();
        mountedDevices = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        mountedDevicesKmemCache = new javax.swing.JCheckBox();
        androidVolProfile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.title")); // NOI18N
        setModal(true);
        setResizable(false);

        org.openide.awt.Mnemonics.setLocalizedText(saveAndroidSettingsButton, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.saveAndroidSettingsButton.text")); // NOI18N
        saveAndroidSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAndroidSettingsButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.jLabel1.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.jPanel1.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(pstree, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.text")); // NOI18N
        pstree.setToolTipText(org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.toolTipText")); // NOI18N
        pstree.setName(""); // NOI18N
        pstree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pstreeActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(pslist, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.pslist.text")); // NOI18N
        pslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pslistActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(limeInfo, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.limeInfo.text")); // NOI18N
        limeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limeInfoActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(arpTable, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.arpTable.text")); // NOI18N
        arpTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arpTableActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(linuxBanner, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.linuxBanner.text")); // NOI18N
        linuxBanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linuxBannerActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(bashHistory, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.bashHistory.text")); // NOI18N
        bashHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bashHistoryActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(bashEnvVar, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.bashEnvVar.text")); // NOI18N
        bashEnvVar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bashEnvVarActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(bashHashTable, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.bashHashTable.text")); // NOI18N
        bashHashTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bashHashTableActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(checkAfInfo, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.checkAfInfo.text")); // NOI18N
        checkAfInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAfInfoActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(checkCredsStruct, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.checkCredsStruct.text")); // NOI18N
        checkCredsStruct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCredsStructActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(checkEvt, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.checkEvt.text")); // NOI18N
        checkEvt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEvtActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(checkModules, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.checkModules.text")); // NOI18N
        checkModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkModulesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(checkSyscall, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.checkSyscall.text")); // NOI18N
        checkSyscall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSyscallActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(checkSyscallArm, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.checkSyscallArm.text")); // NOI18N
        checkSyscallArm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSyscallArmActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(dentryCache, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.dentryCache.text")); // NOI18N
        dentryCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dentryCacheActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(kernelDebugBuffer, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.kernelDebugBuffer.text")); // NOI18N
        kernelDebugBuffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kernelDebugBufferActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(findELF, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.findELF.text")); // NOI18N
        findELF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findELFActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(ifconfigComm, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.ifconfigComm.text")); // NOI18N
        ifconfigComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ifconfigCommActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(enumerateFiles, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.enumerateFiles.text")); // NOI18N
        enumerateFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enumerateFilesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(hiddenKernelModules, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.hiddenKernelModules.text")); // NOI18N
        hiddenKernelModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiddenKernelModulesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(iomemComm, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.iomemComm.text")); // NOI18N
        iomemComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iomemCommActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(keyboardNotifiers, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.keyboardNotifiers.text")); // NOI18N
        keyboardNotifiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyboardNotifiersActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(ldrModules, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.ldrModules.text")); // NOI18N
        ldrModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldrModulesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.jLabel4.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(libraryList, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.libraryList.text")); // NOI18N
        libraryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libraryListActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(appsPromSoc, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.appsPromSoc.text")); // NOI18N
        appsPromSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appsPromSocActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.jLabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(loadedKernelModules, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.loadedKernelModules.text")); // NOI18N
        loadedKernelModules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadedKernelModulesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(listOpenFiles, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.listOpenFiles.text")); // NOI18N
        listOpenFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOpenFilesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(suspiciousProcessMappings, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.suspiciousProcessMappings.text")); // NOI18N
        suspiciousProcessMappings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspiciousProcessMappingsActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(mountedDevices, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.mountedDevices.text")); // NOI18N
        mountedDevices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mountedDevicesActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(mountedDevicesKmemCache, org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.mountedDevicesKmemCache.text")); // NOI18N
        mountedDevicesKmemCache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mountedDevicesKmemCacheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dentryCache)
                    .addComponent(kernelDebugBuffer)
                    .addComponent(findELF)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(checkSyscall)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(checkSyscallArm)
                            .addComponent(limeInfo)
                            .addComponent(arpTable)
                            .addComponent(linuxBanner)
                            .addComponent(bashHistory)
                            .addComponent(bashEnvVar)
                            .addComponent(bashHashTable)
                            .addComponent(checkAfInfo)
                            .addComponent(checkCredsStruct)
                            .addComponent(checkEvt)
                            .addComponent(checkModules)
                            .addComponent(ifconfigComm)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(enumerateFiles)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pstree)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mountedDevices)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(suspiciousProcessMappings)
                            .addComponent(listOpenFiles)
                            .addComponent(loadedKernelModules)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(appsPromSoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(libraryList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ldrModules)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(keyboardNotifiers)
                            .addComponent(hiddenKernelModules)
                            .addComponent(pslist)
                            .addComponent(iomemComm)
                            .addComponent(mountedDevicesKmemCache))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limeInfo)
                    .addComponent(hiddenKernelModules))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arpTable)
                    .addComponent(iomemComm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linuxBanner)
                    .addComponent(keyboardNotifiers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bashHistory)
                    .addComponent(ldrModules)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bashEnvVar)
                    .addComponent(libraryList)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bashHashTable)
                    .addComponent(appsPromSoc)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAfInfo)
                    .addComponent(loadedKernelModules))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkCredsStruct)
                    .addComponent(listOpenFiles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkEvt)
                    .addComponent(suspiciousProcessMappings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkModules)
                    .addComponent(mountedDevices)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSyscall)
                    .addComponent(jLabel2)
                    .addComponent(mountedDevicesKmemCache))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkSyscallArm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dentryCache)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kernelDebugBuffer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findELF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ifconfigComm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enumerateFiles)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(pslist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pstree)
                        .addGap(18, 18, 18))))
        );

        androidVolProfile.setText(org.openide.util.NbBundle.getMessage(AndroidPluginSetup.class, "AndroidPluginSetup.androidVolProfile.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(357, Short.MAX_VALUE)
                        .addComponent(saveAndroidSettingsButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(androidVolProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 233, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(androidVolProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveAndroidSettingsButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveAndroidSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAndroidSettingsButtonActionPerformed
        // TODO add your handling code here:

        //Set Volatility Profile
        volProfile = androidVolProfile.getText();

        AndroidPluginSetup.this.dispose();
    }//GEN-LAST:event_saveAndroidSettingsButtonActionPerformed

    //Set Volatility Plugins list
    private void pstreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pstreeActionPerformed
        // TODO add your handling code here:
        //line to add plugin to ArrayList if box selected
        if (pstree.isSelected()) {

            plugins.add("linux_pstree");
 
        }
        else if(!pstree.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_pstree"));
            
        }
    }//GEN-LAST:event_pstreeActionPerformed

    private void pslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pslistActionPerformed
        // TODO add your handling code here:
        if (pslist.isSelected()) {
            //line to add plugin to ArrayList if box selected
            plugins.add("linux_pslist");
        }
        else if(!pslist.isSelected()){
            //line to remove plugin to ArrayList if box selected
            plugins.remove(plugins.indexOf("linux_pslist"));
        }
       
    }//GEN-LAST:event_pslistActionPerformed

    private void limeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limeInfoActionPerformed
        // TODO add your handling code here:
        if (limeInfo.isSelected()) {

            plugins.add("limeinfo");
        }
        else if(!limeInfo.isSelected()){
            //line to remove plugin to ArrayList if box selected
            plugins.remove(plugins.indexOf("limeinfo"));   
        }
    }//GEN-LAST:event_limeInfoActionPerformed

    private void arpTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arpTableActionPerformed
        // TODO add your handling code here:
        if (arpTable.isSelected()) {

            plugins.add("linux_arp");
        }
        else if(!arpTable.isSelected()){
            //line to remove plugin to ArrayList if box selected
            plugins.remove(plugins.indexOf("linux_arp"));   
        }
    }//GEN-LAST:event_arpTableActionPerformed

    private void linuxBannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linuxBannerActionPerformed
        // TODO add your handling code here:
        if (linuxBanner.isSelected()) {

            plugins.add("linux_banner");
        }
        else if(!linuxBanner.isSelected()){
            //line to remove plugin to ArrayList if box selected
            plugins.remove(plugins.indexOf("linux_banner"));   
        }
    }//GEN-LAST:event_linuxBannerActionPerformed

    private void bashHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bashHistoryActionPerformed
        // TODO add your handling code here:
        if (bashHistory.isSelected()) {

            plugins.add("linux_bash");
        }
        else if(!bashHistory.isSelected()){
            //line to remove plugin to ArrayList if box selected
            plugins.remove(plugins.indexOf("linux_bash"));   
        }
    }//GEN-LAST:event_bashHistoryActionPerformed

    private void bashEnvVarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bashEnvVarActionPerformed
        // TODO add your handling code here:
        if (bashEnvVar.isSelected()) {

            plugins.add("linux_bash_env");
        }
        else if(!bashEnvVar.isSelected()){
            //line to remove plugin to ArrayList if box selected
            plugins.remove(plugins.indexOf("linux_bash_env"));   
        }
    }//GEN-LAST:event_bashEnvVarActionPerformed

    private void bashHashTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bashHashTableActionPerformed
        // TODO add your handling code here:
        if (bashHashTable.isSelected()) {

            plugins.add("linux_bash_hash");
        }
        else if(!bashHashTable.isSelected()){
            //line to remove plugin to ArrayList if box selected
            plugins.remove(plugins.indexOf("linux_bash_hash"));   
        }
    }//GEN-LAST:event_bashHashTableActionPerformed

    private void checkAfInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAfInfoActionPerformed
        // TODO add your handling code here:
        //line to add plugin to ArrayList if box selected
        if (checkAfInfo.isSelected()) {

            plugins.add("linux_check_afinfo");
        }
        else if(!checkAfInfo.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_check_afinfo"));   
        }
    }//GEN-LAST:event_checkAfInfoActionPerformed

    private void checkCredsStructActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCredsStructActionPerformed
        // TODO add your handling code here:
        //line to add plugin to ArrayList if box selected
        if (checkCredsStruct.isSelected()) {

            plugins.add("linux_check_creds");
        }
        else if(!checkCredsStruct.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_check_creds"));   
        }
    }//GEN-LAST:event_checkCredsStructActionPerformed

    private void checkEvtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEvtActionPerformed
        // TODO add your handling code here:
        if (checkEvt.isSelected()) {

            plugins.add("linux_check_evt_arm");
        }
        else if(!checkEvt.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_check_evt_arm"));   
        }
    }//GEN-LAST:event_checkEvtActionPerformed

    private void checkModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkModulesActionPerformed
        // TODO add your handling code here:
        if (checkModules.isSelected()) {

            plugins.add("linux_check_modules");
        }
        else if(!checkModules.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_check_modules"));   
        }
    }//GEN-LAST:event_checkModulesActionPerformed

    private void checkSyscallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSyscallActionPerformed
        // TODO add your handling code here:
        if (checkSyscall.isSelected()) {

            plugins.add("linux_check_syscall");
        }
        else if(!checkSyscall.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_check_syscall"));   
        }
    }//GEN-LAST:event_checkSyscallActionPerformed

    private void checkSyscallArmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSyscallArmActionPerformed
        // TODO add your handling code here:
        if (checkSyscallArm.isSelected()) {

            plugins.add("linux_check_syscall_arm");
        }
        else if(!checkSyscallArm.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_check_syscall_arm"));   
        }
    }//GEN-LAST:event_checkSyscallArmActionPerformed

    private void dentryCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dentryCacheActionPerformed
        // TODO add your handling code here:
         if (dentryCache.isSelected()) {

            plugins.add("linux_dentry_cache");
        }
        else if(!dentryCache.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_dentry_cache"));   
        }
    }//GEN-LAST:event_dentryCacheActionPerformed

    private void kernelDebugBufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kernelDebugBufferActionPerformed
        // TODO add your handling code here:
         if (kernelDebugBuffer.isSelected()) {

            plugins.add("linux_dmesg");
        }
        else if(!kernelDebugBuffer.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_dmesg"));   
        }
    }//GEN-LAST:event_kernelDebugBufferActionPerformed

    private void findELFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findELFActionPerformed
        // TODO add your handling code here:
         if (findELF.isSelected()) {

            plugins.add("linux_elfs");
        }
        else if(!findELF.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_elfs"));   
        }
    }//GEN-LAST:event_findELFActionPerformed

    private void ifconfigCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ifconfigCommActionPerformed
        // TODO add your handling code here:
        if (ifconfigComm.isSelected()) {

            plugins.add("linux_ifconfig");
        }
        else if(!ifconfigComm.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_ifconfig"));   
        }
    }//GEN-LAST:event_ifconfigCommActionPerformed

    private void enumerateFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enumerateFilesActionPerformed
        // TODO add your handling code here:
        if (enumerateFiles.isSelected()) {

            plugins.add("linux_enumerate_files");
        }
        else if(!enumerateFiles.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_enumerate_files"));   
        }
    }//GEN-LAST:event_enumerateFilesActionPerformed

    private void hiddenKernelModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiddenKernelModulesActionPerformed
        // TODO add your handling code here:
        if (hiddenKernelModules.isSelected()) {

            plugins.add("linux_hidden_modules");
        }
        else if(!hiddenKernelModules.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_hidden_modules"));   
        }
    }//GEN-LAST:event_hiddenKernelModulesActionPerformed

    private void iomemCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iomemCommActionPerformed
        // TODO add your handling code here:
        if (iomemComm.isSelected()) {

            plugins.add("linux_iomem");
        }
        else if(!iomemComm.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_iomem"));   
        }
    }//GEN-LAST:event_iomemCommActionPerformed

    private void keyboardNotifiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyboardNotifiersActionPerformed
        // TODO add your handling code here:
        if (keyboardNotifiers.isSelected()) {

            plugins.add("linux_keyboard_notifiers");
        }
        else if(!keyboardNotifiers.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_keyboard_notifiers"));   
        }
    }//GEN-LAST:event_keyboardNotifiersActionPerformed

    private void ldrModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldrModulesActionPerformed
        // TODO add your handling code here:
        if (ldrModules.isSelected()) {

            plugins.add("linux_ldrmodules");
        }
        else if(!ldrModules.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_ldrmodules"));   
        }
    }//GEN-LAST:event_ldrModulesActionPerformed

    private void libraryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libraryListActionPerformed
        // TODO add your handling code here:
        if (libraryList.isSelected()) {

            plugins.add("linux_library_list");
        }
        else if(!libraryList.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_library_list"));   
        }
    }//GEN-LAST:event_libraryListActionPerformed

    private void appsPromSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appsPromSocActionPerformed
        // TODO add your handling code here:
        if (appsPromSoc.isSelected()) {

            plugins.add("linux_list_raw");
        }
        else if(!appsPromSoc.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_list_raw"));   
        }
    }//GEN-LAST:event_appsPromSocActionPerformed

    private void loadedKernelModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadedKernelModulesActionPerformed
        // TODO add your handling code here:
        if (loadedKernelModules.isSelected()) {

            plugins.add("linux_lsmod");
        }
        else if(!loadedKernelModules.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_lsmod"));   
        }
    }//GEN-LAST:event_loadedKernelModulesActionPerformed

    private void listOpenFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOpenFilesActionPerformed
        // TODO add your handling code here:
         if (listOpenFiles.isSelected()) {

            plugins.add("linux_lsof");
        }
        else if(!listOpenFiles.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_lsof"));   
        }
    }//GEN-LAST:event_listOpenFilesActionPerformed

    private void suspiciousProcessMappingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspiciousProcessMappingsActionPerformed
        // TODO add your handling code here:
        if (suspiciousProcessMappings.isSelected()) {

            plugins.add("linux_malfind");
        }
        else if(!suspiciousProcessMappings.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_malfind"));   
        }
    }//GEN-LAST:event_suspiciousProcessMappingsActionPerformed

    private void mountedDevicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mountedDevicesActionPerformed
        // TODO add your handling code here:        
        if (mountedDevices.isSelected()) {

            plugins.add("linux_mount");
        }
        else if(!mountedDevices.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_mount"));   
        }
    }//GEN-LAST:event_mountedDevicesActionPerformed

    private void mountedDevicesKmemCacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mountedDevicesKmemCacheActionPerformed
        // TODO add your handling code here:
        if (mountedDevices.isSelected()) {

            plugins.add("linux_mount_cache");
        }
        else if(!mountedDevices.isSelected()){
            //line to remove plugin from ArrayList if box not selected
            plugins.remove(plugins.indexOf("linux_mount_cache"));   
        }
    }//GEN-LAST:event_mountedDevicesKmemCacheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndroidPluginSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndroidPluginSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndroidPluginSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndroidPluginSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AndroidPluginSetup dialog = new AndroidPluginSetup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField androidVolProfile;
    private javax.swing.JCheckBox appsPromSoc;
    private javax.swing.JCheckBox arpTable;
    private javax.swing.JCheckBox bashEnvVar;
    private javax.swing.JCheckBox bashHashTable;
    private javax.swing.JCheckBox bashHistory;
    private javax.swing.JCheckBox checkAfInfo;
    private javax.swing.JCheckBox checkCredsStruct;
    private javax.swing.JCheckBox checkEvt;
    private javax.swing.JCheckBox checkModules;
    private javax.swing.JCheckBox checkSyscall;
    private javax.swing.JCheckBox checkSyscallArm;
    private javax.swing.JCheckBox dentryCache;
    private javax.swing.JCheckBox enumerateFiles;
    private javax.swing.JCheckBox findELF;
    private javax.swing.JCheckBox hiddenKernelModules;
    private javax.swing.JCheckBox ifconfigComm;
    private javax.swing.JCheckBox iomemComm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox kernelDebugBuffer;
    private javax.swing.JCheckBox keyboardNotifiers;
    private javax.swing.JCheckBox ldrModules;
    private javax.swing.JCheckBox libraryList;
    private javax.swing.JCheckBox limeInfo;
    private javax.swing.JCheckBox linuxBanner;
    private javax.swing.JCheckBox listOpenFiles;
    private javax.swing.JCheckBox loadedKernelModules;
    private javax.swing.JCheckBox mountedDevices;
    private javax.swing.JCheckBox mountedDevicesKmemCache;
    private javax.swing.JCheckBox pslist;
    private javax.swing.JCheckBox pstree;
    private javax.swing.JButton saveAndroidSettingsButton;
    private javax.swing.JCheckBox suspiciousProcessMappings;
    // End of variables declaration//GEN-END:variables
}
